### ISSUE TITLE
Add action for eslint

### ISSUE THREAD

**Issue by gegoune** [clog-rocks/frontend#16]
Ensures proper code styling.

Example:
```
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
```
